version: 2
jobs:
  build:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          command: |
            yarn
            yarn lint
            yarn test
            yarn build
